name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      working-directory: website
      run: npm install
    - name: publish docs
      working-directory: website
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        COMMIT_MSG: |
          publish docs
          skip-checks: true
        GIT_USER: castlemilk
        CURRENT_BRANCH: master
      
      run: |
        git config --global user.email "${GIT_USER}@users.noreply.github.com"
        git config --global user.name "${GIT_USER}"
        echo "machine github.com login ${GIT_USER} password ${GITHUB_TOKEN}" > ~/.netrc
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run publish-gh-pages
