name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: cd website; npm install
    - name: publish docs
      run: GIT_USER=castlemilk CURRENT_BRANCH=master USE_SSH=true cd website; npm run publish-gh-pages
