name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      working-directory: website
      run: npm install
    - name: publish docs
      working-directory: website
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          publish docs
          skip-checks: true
        GIT_USER: castlemilk
        CURRENT_BRANCH: master
      
      run: |
        git config user.email "ben.ebsworth@gmail.com"
        git config user.name ${GIT_USER}
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run publish-gh-pages
