name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      working-directory: website
      run: npm install
    - name: publish docs
      working-directory: website
      run: GIT_USER=castlemilk CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages
