name: CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      working-directory: website
      run: npm install
    - name: publish docs
      working-directory: website
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          publish docs
          skip-checks: true
      
      run: |
        GIT_USER=actions-pipeline CURRENT_BRANCH=master npm run publish-gh-pages
